### ISSUE TITLE
Question: Why is the trpc client initialized multiple times in the `.svelte` files?

### ISSUE THREAD

**Issue by vishalbalaji** [icflorescu/trpc-sveltekit-example#11]
I apologize if this is a dumb question, but I am quite new to tRPC and still trying to figure stuff out. Why, in every method in the `.svelte` templates is the `trpc` client invoked for each query, mutation, etc? Eg,

```ts
const reloadBooks = async () => {
  loading = true;
  data.books = await trpc().query('books:browse', query);
  loading = false;
};
```

This doesn't seem to be a thing in the server code, where `trpc()` is invoked once and is then reused mutiple times. Won't doing that work in the client code?

**Comment by icflorescu** [comment]
Thanks for raising!
I think this doesn't happen anymore in the new version.
Please feel free to reopen if necessary.
