### ISSUE TITLE
"npm run build" throws superjson.registerCustom is not a function

### ISSUE THREAD

**Issue by atresnjo** [icflorescu/trpc-sveltekit-example#3]
Hey, thanks for the great work on setting everything up! Wanted to give tRPC with SvelteKit a try, but the example doesn't build. It works fine when ran locally, but the build itself fails.

![image](https://user-images.githubusercontent.com/41112852/154801505-ac05ac2c-a70f-4e36-a18d-d267e130499d.png)

Thanks! 💯

**Comment by ambiguous48** [comment]
Does your svelte.config.js have the following? Notably the `vite` part.

```ts
  kit: {
    adapter: adapter(),
    vite:
      process.env.NODE_ENV === 'production'
        ? {
            ssr: {
              noExternal: ['superjson']
            }
          }
        : undefined
  }
  ```
  
  From this [section](https://github.com/icflorescu/trpc-sveltekit#recipes--caveats-) of the docs.

**Comment by atresnjo** [comment]
Yeah. I'm using this repo. 👍 

![image](https://user-images.githubusercontent.com/41112852/154811331-7db8b8ad-e562-4abe-bdce-7dd13fe34f76.png)

**Comment by ambiguous48** [comment]
The reason I asked is because when I comment out the enitre `vite` property, I get the exact same issue you're getting in the screenshot. To eliminate if your original issue is caused by this, try forcing the condition to true and see if it builds:

```diff
-      process.env.NODE_ENV !== 'production'
+      true || process.env.NODE_ENV !== 'production'
```

**Comment by atresnjo** [comment]
That worked, thank you very much. Obviously, I would need to set NODE_ENV to production, for it to work. Duh me, thanks again!

**Comment by icflorescu** [comment]
Thanks for clearing things out, @ambiguous48!

It's in the [trpc-sveltekit](https://github.com/icflorescu/trpc-sveltekit) docs: https://github.com/icflorescu/trpc-sveltekit#configure-superjson-to-correctly-handle-decimaljs--prismadecimal

To all: do you have any suggestion on how to make this clearer?

**Comment by atresnjo** [comment]
The issue wasn't missing documentation, in my opinion, just a slight oversight not seeing that the NODE_ENV environment variable is not being set anywhere. Maybe for this example just have the build script set the environment variable?
```js
"build": "cross-env NODE_ENV=production && svelte-kit build",
```

**Comment by icflorescu** [comment]
> The issue wasn't missing documentation, in my opinion, just a slight oversight not seeing that the NODE_ENV environment variable is not being set anywhere. Maybe for this example just have the build script set the environment variable?
> 
> ```js
> "build": "cross-env NODE_ENV=production && svelte-kit build",
> ```

I don't know, is it really necessary? I was under the impression that `NODE_ENV` was automatically set to `production` when running `svelte-kit build`...

**Comment by atresnjo** [comment]
> > The issue wasn't missing documentation, in my opinion, just a slight oversight not seeing that the NODE_ENV environment variable is not being set anywhere. Maybe for this example just have the build script set the environment variable?
> > ```js
> > "build": "cross-env NODE_ENV=production && svelte-kit build",
> > ```
> 
> I don't know, is it really necessary? I was under the impression that `NODE_ENV` was automatically set to `production` when running `svelte-kit build`...

Yep, I thought the same. My env could be somehow broken, at least it didn't set it for me.
