### ISSUE TITLE
pnpm doesn't work

### ISSUE THREAD

**Issue by Wazarr94** [icflorescu/trpc-sveltekit-example#5]
Oddly this doesn't happen with yarn and npm.
After installing with pnpm I get the following error:

![image](https://user-images.githubusercontent.com/39807740/177408235-104b4b0a-7a57-4b91-897d-47ffa1eb1d0d.png)

Any ideas?

**Comment by ambiguous48** [comment]
How are you importing your Prisma Client? Try this:

```ts
// src/lib/prismaClient.ts
import type { PrismaClient as PrismaClientType } from "@prisma/client";
import pkg from "@prisma/client";

const { PrismaClient } = pkg;

const prismaClient =
	// @ts-ignore
	global.prismaClient || new PrismaClient();

if (process.env.NODE_ENV === "development") {
	// @ts-ignore
	global.prismaClient = prismaClient;
}

export default prismaClient as PrismaClientType;
```

**Comment by icflorescu** [comment]
I cannot reproduce this, at least not after updating all packages to newest versions as of today.
I just tested with `pnpm` and everything works as expected.

Can you please pull the latest changes and try again?

**Comment by Wazarr94** [comment]
Might be a bug from my system, in any case I don't think this repository is the best to file an issue in for this issue
